apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: grafana-deployment-nautilus
  name: grafana-deployment-nautilus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-deployment-nautilus
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-deployment-nautilus
    spec:
      containers:
      - image: grafana/grafana
        name: grafana-container
        resources: {}
        ports:
        - containerPort: 3000
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-deployment-nautilus
spec:
  type: NodePort
  selector:
    app: grafana-deployment-nautilus
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000