apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lemp-wp
  name: lemp-wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lemp-wp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lemp-wp
    spec:
      containers:
      - image: webdevops/php-nginx:alpine-3-php7
        name: nginx-php-container
        resources: {}
        volumeMounts:
        - name: php-config-volume
          mountPath: /opt/docker/etc/php/php.ini
          subPath: php.ini
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-db-url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-user-pass-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-user-pass-password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-host
        ports:
        - containerPort: 80                                                  
      - image: mysql:5.6
        name: mysql-container
        resources: {}
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-db-url
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-user-pass-username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-user-pass-password
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: lemp-secret
              key: mysql-host
        ports:
        - containerPort: 3306
      volumes:
      - name: php-config-volume
        configMap:
          name: php-config
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lemp-service
spec:
  type: NodePort
  selector:
    app: lemp-wp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: lemp-wp
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-config
data:
  php.ini: |
    variables_order: "EGPCS"
---
apiVersion: v1
kind: Secret
metadata:
  name: lemp-secret
type: Opaque
data:
  mysql-root-pass: UjAwdA==
  mysql-user-pass-username: a29kZWtsb3VkX2FpbQ==
  mysql-user-pass-password: a3NIODVVSmpoYg==
  mysql-db-url: a29kZWtsb3VkX2RiNg==
  mysql-host: bXlzcWwtc2VydmljZQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS kodekloud_db6;
    CREATE USER 'kodekloud_aim'@'localhost' IDENTIFIED BY 'ksH85UJjhb';
    GRANT ALL PRIVILEGES ON kodekloud_db6.* TO 'kodekloud_aim'@'%';
    FLUSH PRIVILEGES;