apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node
  name: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node
    spec:
      containers:
      - image: gcr.io/kodekloud/centos-ssh-enabled:node
        name: centos-ssh-enabled
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  selector:
    app: node
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30012