apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: pod-nautilus
  name: pod-nautilus
spec:
  containers:
  - image: nginx:latest
    name: container-nautilus
    resources: {}
    volumeMounts:
    - name: pvc-nautilus
      mountPath: "/mnt/devops"
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name : pvc-nautilus
    persistentVolumeClaim:
      claimName: pvc-nautilus
status: {}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "/mnt/devops"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
spec:
  type: NodePort
  selector:
    app: pod-nautilus
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008