apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-devops
  name: secret-devops
spec:
  volumes:
    - name: blog-secret
      secret:
        secretName: blog
  containers:
  - image: fedora:latest
    name: secret-container-devops
    resources: {}
    command: ["/bin/sh", "-c", "sleep infinity"]
    volumeMounts:
      - name: blog-secret
        readOnly: true
        mountPath: "/opt/apps"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
data:
  blog.txt: NWVjdXIzCg==
kind: Secret
metadata:
  creationTimestamp: null
  name: blog