apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: time-check
  name: time-check
  namespace: datacenter
spec:
  containers:
  - image: busybox:latest
    name: time-check
    resources: {}
    command:
    - while true; do date; sleep $TIME_FREQ;done > /opt/itadmin/time/time-check.log
    env: 
    - name: TIME_FREQ
      valueFrom:
        configMapKeyRef:
          name: time-config
          key: TIME_FREQ
    volumeMounts:
    - mountPath: /opt/itadmin/time
      name: log-volume
  volumes:
    - name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}